crm:
    groupSize: 7
    rankStrategy:
        1: 2,3,4,5,6,7
        2: 4,5,3,6,7
        3: 6,7,4,5
        4: 3,5,6,7
        5: 3,6,7
   # deMergeGroup:
   #     - {1: 2,2: 4,3: 5}
   #     - {1: 3,2: 6,3: 7}
    initPoint: 0
    rewardMember: 2000
    rewardParent: 6000
security:
    enable-csrf: false
    basic:
        enabled: false
